Document the new parameter resolveArtifacts of RESOLVE_ONLY Maven rep…
project-ncl/bacon pull request #950
Opened 2022-06-22 13:19 UTC by ppalaga

…o generation strategy

2022-06-30 07:22 UTC, ppalaga commented
I have added a section about setting a Local caching proxy for Indy in bd7325b . 
@saumya1singh @harshmadhani @cunningt this is handy when generating the Maven repo zip locally on a slow & flaky connection. In this way `pig` can re-use the artifacts successfuly downloaded in the past, even though those previous `pig` invocations may have failed due to network issues or similar.

2022-06-30 07:23 UTC, ppalaga commented
cc @svkcemk

2022-07-06 20:52 UTC, thescouser89 requested changes

2022-07-06 20:54 UTC, thescouser89 commented
Hi @ppalaga !

I wanted to apologize for the slow review on your 2 PRs. We've been hit by public holidays and another urgent initiative whose deadline was very close.

2022-07-08 09:38 UTC, ppalaga commented on guide/configuration.md
> +# Local caching proxy for Indy
Thanks, done.

2022-07-11 17:55 UTC, thescouser89 approved these changes

2022-07-11 17:55 UTC, merged